### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by D063520** [marcocor/smaph-erd#4]
Sorry again,

apparently there is an issue with another dependency:

Failed to execute goal on project smaph: Could not resolve dependencies for project it.acubelab.smaph:smaph:jar:0.0.1-SNAPSHOT: Could not find artifact it.cnr.isti.hpc:hpc-utils:jar:0.0.5 in central

Thank you
Dennis

**Comment by marcocor** [comment]
Hi. Did you checkout the latest commit b74af7a97201e7a104cae96aef2bf2f0fe062f69? It should be pointing to hpc-utils 0.0.7, which you can download and install following the instruction in the README.md.

**Comment by D063520** [comment]
I didn't see that you also updated the README. Thank you!
